export default [
    {
        name: 'Girafes',
        air: Math.round(Math.random()*25),
        water: Math.round(Math.random()*25),
        fire: Math.round(Math.random()*25),
        earth: Math.round(Math.random()*25),
        bonus: (Math.random() > 0.5 ? -1 : 1) * Math.round(Math.random() * 100),
        color: 'linear-gradient(to right, #FE9401,#FF6E00)',
    },
    {
        name: 'Crocodiles',
        air: Math.round(Math.random()*25),
        water: Math.round(Math.random()*25),
        fire: Math.round(Math.random()*25),
        earth: Math.round(Math.random()*25),
        bonus: (Math.random() > 0.5 ? -1 : 1) * Math.round(Math.random() * 100),
        color: 'linear-gradient(to right, #1ecd64, #1AB639)',
    },
    {
        name: 'Chiens',
        air: Math.round(Math.random()*25),
        water: Math.round(Math.random()*25),
        fire: Math.round(Math.random()*25),
        earth: Math.round(Math.random()*25),
        bonus: (Math.random() > 0.5 ? -1 : 1) * Math.round(Math.random() * 100),
        color: 'linear-gradient(to right, #8d6225,#713100)',
    },
    {
        name: 'Lapins',
        air: Math.round(Math.random()*25),
        water: Math.round(Math.random()*25),
        fire: Math.round(Math.random()*25),
        earth: Math.round(Math.random()*25),
        bonus: (Math.random() > 0.5 ? -1 : 1) * Math.round(Math.random() * 100),
        color: 'linear-gradient(to right, #3f7dfa, #133fa0)',
    },
    {
        name: 'Lionceaux',
        air: Math.round(Math.random()*25),
        water: Math.round(Math.random()*25),
        fire: Math.round(Math.random()*25),
        earth: Math.round(Math.random()*25),
        bonus: (Math.random() > 0.5 ? -1 : 1) * Math.round(Math.random() * 100),
        color: 'linear-gradient(to right, #FE3A2F,#E70401)',
    },
    {
        name: 'Pythons',
        air: Math.round(Math.random()*25),
        water: Math.round(Math.random()*25),
        fire: Math.round(Math.random()*25),
        earth: Math.round(Math.random()*25),
        bonus: (Math.random() > 0.5 ? -1 : 1) * Math.round(Math.random() * 100),
        color: 'linear-gradient(to right, #3f8b00,#00a23b)',
    }
];
